# Generated by Django 5.0.4 on 2024-04-16 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fechas_Importantes",
            fields=[
                ("idFecha", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fechaInicio",
                    models.DateTimeField(verbose_name="fecha inicio evento"),
                ),
                ("fechaFinal", models.DateTimeField(verbose_name="fecha fin evento")),
                ("nombreEvento", models.TextField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name="Trabajadores",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.TextField(blank=True, max_length=5000)),
                ("apellido", models.TextField(blank=True, max_length=5000)),
                ("diasVacaciones", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Vacaciones",
            fields=[
                ("idVacaciones", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fechaInicio",
                    models.DateTimeField(verbose_name="fecha inicio vacaciones"),
                ),
                (
                    "fechaFinal",
                    models.DateTimeField(verbose_name="fecha fin vacaciones"),
                ),
                (
                    "idTrabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.trabajadores",
                    ),
                ),
            ],
        ),
    ]
