# Generated by Django 5.0.4 on 2024-04-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_vacaciones_aprobado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fechas_importantes",
            name="fechaFinal",
            field=models.DateField(verbose_name="fecha fin evento"),
        ),
        migrations.AlterField(
            model_name="fechas_importantes",
            name="fechaInicio",
            field=models.DateField(verbose_name="fecha inicio evento"),
        ),
    ]
